### ISSUE TITLE
PVP

### ISSUE THREAD

**Issue by Matthww** [BlockHorizons/FactionsPE#10]
Allow people with a faction to pvp a person without a faction even though they are not in each others territory.

**Comment by Kris-Driv** [comment]
That already exists, there is setting in config file for that.

**Comment by Matthww** [comment]
Yea but only if the faction less member enters someone's territory. I want all the people to be aple to pvp with eachother.

**Comment by Matthww** [comment]
Also it would be nice to see info about someone else's faction. 

Like /f info (something similiar but pocket size friendly)
![image](https://cloud.githubusercontent.com/assets/3885070/26190283/e9128fd4-3ba8-11e7-9107-14bba8c8494d.png)

**Comment by Kris-Driv** [comment]
Done. Thanks!
