### ISSUE TITLE
Add command for displaying faction info

### ISSUE THREAD

**Issue by TheDiamondYT1** [BlockHorizons/FactionsPE#11]
Take a look at https://github.com/TheDiamondYT1/PocketFactions/blob/master/src/TheDiamondYT/PocketFactions/command/CommandShow.php

**Comment by Sandertv** [comment]
I haven't looked into the plugin too much yet, but it seems like there's AT LEAST something like it: https://github.com/BlockHorizons/FactionsPE/issues/10#issuecomment-302319323

**Comment by TheDiamondYT1** [comment]
@Sandertv Ive checked, there isn't.

**Comment by Sandertv** [comment]
Description command seems to be on the TODO list for initial public release.

**Comment by TheDiamondYT1** [comment]
@Sandertv An info command and description command are different things

**Comment by Sandertv** [comment]
The suggestion has kinda been made in #10 already.

**Comment by TheDiamondYT1** [comment]
@Sandertv I know, but that was posted in an issue  about something else. So, to make it more known, i created a *seperate* issue for it.

**Comment by Sandertv** [comment]
Is it alright if I close this and just add it to the TODO list?

**Comment by Kris-Driv** [comment]
Hold on, did I solve this?

**Comment by Kris-Driv** [comment]
I did made this one year ago, but I updated this https://github.com/BlockHorizons/FactionsPE/commit/d48c04d445d756dc91c9790fce529fa6e1bfc8a3
