### ISSUE TITLE
How to get Faction tags to show

### ISSUE THREAD

**Issue by XxParkerGamesxX** [BlockHorizons/FactionsPE#12]
I'm using purechat I want Faction names to show I know you have a built in chat system but it doesn't support the ranks do you know anyway I can use the faction names and ranks at the same time

**Comment by Sandertv** [comment]
Try this modified version of purechat: https://github.com/Chris-Prime/PureChat

**Comment by XxParkerGamesxX** [comment]
its still not working

**Comment by poustmal** [comment]
you should setformat your groups like: {fac_name}{fac_rank} first and then it will probably work idk

**Comment by Chris-Prime** [comment]
https://github.com/BlockHorizons/FactionsPE/blob/reborn/README.md#purechat-support
