### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by SourSmirnoff** [BlockHorizons/FactionsPE#17]
No error, im sorry for no details about an error.
My coding is not as advanced so i cant find the issue either.

What happens:
Server is perfectly fine, i upload this plugin, server starts halfway and enters a crash loop.

**Comment by Thunder33345** [comment]
show logs!!

**Comment by SourSmirnoff** [comment]
like i said, it doesnt give any critical error or anything. it just crashes, it could have to do with the lints and code warnings they showed on https://poggit.pmmp.io/ci/BlockHorizons/FactionsPE/~/dev:11

again i have tried a rundown of the code y self but am not that advanced to tackle a big project as this.

**Comment by SourSmirnoff** [comment]
it does not create a crash log

**Comment by SourSmirnoff** [comment]
Here we are, i have retested on a clean server to try to develop error:


12.07 13:56:50 [Server] Server thread/EMERGENCY Please upload the "/crashdumps/Wed_Jul_12-14.56.50-MDT_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
12.07 13:56:50 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
12.07 13:56:50 [Server] INFO Fatal error: Declaration of localizer\Translatable::getText() must be compatible with pocketmine\event\TextContainer::getText(): string in phar:///plugins/FactionsPE_v0.9.8.6 (2).phar/src/localizer/Translatable.php on line 6

**Comment by Thunder33345** [comment]
lint: Syntax error detected in src/factions/command/CreateFaction.php:
maybe contributing but others wouldnt cause anything
you should also share the crashdump on somewhere like ghostbin.com and paste the link here
