### ISSUE TITLE
f top

### ISSUE THREAD

**Issue by SourSmirnoff** [BlockHorizons/FactionsPE#18]
13.07 14:48:15 [Server] Server thread/CRITICAL Exception: "undefined flag 'inf_power'" (EXCEPTION) in "FactionsPE_v0.9.8.6.phar/src/factions/entity/Faction" at line 186
13.07 14:48:15 [Server] Server thread/CRITICAL Unhandled exception executing command 'f top' in faction: undefined flag 'inf_power'

In-Game- an unknown error occured while attempting to perform this command

**Comment by SourSmirnoff** [comment]
f disband:

13.07 14:55:33 [Server] Server thread/CRITICAL Exception: "undefined flag 'permanent'" (EXCEPTION) in "FactionsPE_v0.9.8.6.phar/src/factions/entity/Faction" at line 186
13.07 14:55:33 [Server] Server thread/CRITICAL Unhandled exception executing command 'f disband' in faction: undefined flag 'permanent'

**Comment by Kris-Driv** [comment]
Please enable debugging and show us your server version.

**Comment by xXSirGamesXx** [comment]
Its kind of a weird issue. Whenever i reinstall the plugin all the cmds work fine but then after a while it starts doing it again.

**Comment by SourSmirnoff** [comment]
Thats what im having too^^

The plugin works for a while but then Commands just randomly stop working

**Comment by xXSirGamesXx** [comment]
It happened after i edited something in the config.

**Comment by Kris-Driv** [comment]
I'm not able to reproduce this, can anyone give me more information?

**Comment by Kris-Driv** [comment]
I did some changes to permissions, lets see if that fix this.

**Comment by Kris-Driv** [comment]
Fixed.
