### ISSUE TITLE
How to set safezone.

### ISSUE THREAD

**Issue by xXSirGamesXx** [BlockHorizons/FactionsPE#21]
I was wondering how i could set the safezone in a world.

**Comment by Kris-Driv** [comment]
```
/f override
/f claim one safezone
/f override
```
You can claim for any faction while you are in admin/override mode

**Comment by xXSirGamesXx** [comment]
ALso how do i make an area where people cant claim

**Comment by Kris-Driv** [comment]
Players can't overclaim land from Safezone as it has infinity power flag. It's not true if you have mis-configured your config.
