### ISSUE TITLE
players attempting to join 

### ISSUE THREAD

**Issue by SourSmirnoff** [BlockHorizons/FactionsPE#22]
14.07 05:11:38 [Server] Server thread/CRITICAL BadMethodCallException: "Event is not Cancellable" (EXCEPTION) in "src/pocketmine/event/Event" at line 58
14.07 05:11:38 [Server] Server thread/CRITICAL Unhandled exception executing command 'f join Spatch' in faction: Event is not Cancellable

**Comment by Sandertv** [comment]
Could you report back with debug mode set to 2 in the pocketmine.yml?

**Comment by SourSmirnoff** [comment]
sure will do it now

**Comment by Kris-Driv** [comment]
In joining process the MembershipChangeEvent is called, however it is implementing Cancellable interface which means it should work fine. Perhaps you're using old version of FactionsPE? Does this issue still persist?

**Comment by SourSmirnoff** [comment]
I will Upload and test now, should i compile the ZIP from here or use the latest poggit CI?

**Comment by Sandertv** [comment]
Best to use Poggit I'd say.

**Comment by Kris-Driv** [comment]
I lied, MembershipChangeEvent can not be cancelled if - You are creating a faction or leaving it. So this error comes up, It's still not fixed but I haven't seen this error. I'll close this until it re-appears.
