### ISSUE TITLE
Error when using MembershipChangeEvent

### ISSUE THREAD

**Issue by RekkuzaRage** [BlockHorizons/FactionsPE#24]
[Server thread/CRITICAL]: ReflectionException: "Class factions\event\member\MembershipChangeEvent does not exist" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 737
**I receive this error every time my code loads**

`use rekkuzarage\kaliber\Main;

use factions\event\member\MembershipChangeEvent;

class EventListener implements Listener {

	public $kills = [];

	public function __construct(Main $plugin) {
		$this->plugin = $plugin;
		$this->server = $this->plugin->getServer();
		$this->area = $this->server->getPluginManager()->getPlugin("iProtector");
	}

	public function onChange(MembershipChangeEvent $event) {
		$reason = $event->getReason();
		$member = $event->getMember();
		$player = $member->getPlayer();

		if($reason == 0x0 || $reason == 0x4 || $reason == 0x5) {
			$format = $this->plugin->getRank()->createFormat($player);
		}
		else {
			$factionName = $member->getFaction()->getName();
			$format = $this->plugin->getRank()->createFormat($player, $factionName);
		}
		$this->plugin->getPlayer($player)->setChatFormat($format);
	}`

**Comment by Sandertv** [comment]
Hmmm I can't seem to find the issue...

**Comment by RekkuzaRage** [comment]
I believe it might be pocketmine creating this issue.

**Comment by RekkuzaRage** [comment]
Bug only appears on PocketMine API ALPHA-6. Most likely due to API changes.

**Comment by xXSirGamesXx** [comment]
I have something similar to this.
`[19:32:44] [Server thread/INFO]: Enabling FactionsPE v0.9.8.6
[19:32:44] [Server thread/INFO]: [FactionsPE] Enabling...
[19:32:44] [Server thread/INFO]: [FactionsPE] Data provider: YAML
[19:32:44] [Server thread/INFO]: [FactionsPE] 4 faction(s) were loaded
[19:32:45] [Server thread/CRITICAL]: ReflectionException: "Class factions\event\member\MembershipChangeEvent does not exist" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 737
[19:32:45] [Server thread/INFO]: Disabling FactionsPE v0.9.8.6
[19:32:45] [Server thread/INFO]: [FactionsPE] Disabling...
[19:32:45] [Server thread/INFO]: [FactionsPE] Disabled
`

**Comment by Sandertv** [comment]
Alright looking into it.

**Comment by Kris-Driv** [comment]
This seems to only exist in ALPHA7.
