### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/FactionsPE#26]
Fatal error: Cannot use factions\relation\Relation as Relation because the name is already in use in phar:///root/factions/plugins/FactionsPE.phar/src/factions/command/Info.php on line 28

**Comment by ghost** [comment]
11:41:06 [CRITICAL] Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'FactionsPE v1.0.0': Return value of factions\manager\Plots::getFactionAt() must be an instance of factions\entity\Faction, null returned on factions\engine\MainEngine
11:41:06 [CRITICAL] TypeError: "Return value of factions\manager\Plots::getFactionAt() must be an instance of factions\entity\Faction, null returned" (EXCEPTION) in "/plugins/FactionsPE/src/factions/manager/Plots" at line 55
/

**Comment by Kris-Driv** [comment]
I'll fix this asap. By that I mean tomorrow. Thanks for feedback.

**Comment by XDqrkneZ** [comment]
^
