### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by XDqrkneZ** [BlockHorizons/FactionsPE#27]
18:21:04 [INFO] Enabling FactionsPE v1.0.0
18:21:04 [INFO] [FactionsPE] Enabling...
18:21:04 [INFO] [FactionsPE] Data provider: YAML
/
Fatal error: Cannot use factions\relation\Relation as Relation because the name is already in use in /root/test/plugins/FactionsPE-reborn/src/factions/command/Info.php on line 28                                                          18:21:04 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
18:21:04 [EMERGENCY] Please upload the "/root/test/crashdumps/Fri_Jul_21-18.21.04-EDT_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
18:21:04 [INFO] Disabling Commands v1.0.0
18:21:04 [INFO] Disabling WorldProtect v2.3.5
18:21:04 [INFO] Disabling FactionsPE v1.0.0

**Comment by Kris-Driv** [comment]
Seems to be fixed.
