### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XDqrkneZ** [BlockHorizons/FactionsPE#32]
tions\engine\MainEngine
20:40:06 [CRITICAL] InvalidStateException: "Trying to get permissions of closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 649
20:40:06 [CRITICAL] Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'FactionsPE v1.0.0': Trying to get permissions of closed player on factions\engine\MainEngine
20:40:06 [CRITICAL] InvalidStateException: "Trying to get permissions of closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 649
20:40:06 [CRITICAL] Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'FactionsPE v1.0.0': Trying to get permissions of closed player on factions\engine\MainEngine
20:40:06 [CRITICAL] InvalidStateException: "Trying to get permissions of closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 649
20:40:06 [CRITICAL] Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'FactionsPE v1.0.0': Trying to get permissions of closed player on factions\engine\MainEngine
20:40:06 [CRITICAL] InvalidStateException: "Trying to get permissions of closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 649
20:40:06 [CRITICAL] Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'FactionsPE v1.0.0': Trying to get permissions of closed player on factions\engine\MainEngine
20:40:06 [CRITICAL] InvalidStateException: "Trying to get permissions of closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 649

**Comment by Sandertv** [comment]
This is an issue with a third party software. We cannot help you with this.
