### ISSUE TITLE
How to make it work with pure chat

### ISSUE THREAD

**Issue by AyanKR** [BlockHorizons/FactionsPE#36]
How do i /setformat   purechat groups with it so that it shows the group AND the faction PLEASE PLEASE HELP

**Comment by Kris-Driv** [comment]
There is no official support for FactionsPE. However I've made fork (https://github.com/Chris-Prime/PureChat which does support this plugin. NOTE: chat-formatter must be set to false in order to allow PureChat format your chat instead.

**Comment by servantthought** [comment]
What is chat-format and how do I set it to false?

"There is no official support for FactionsPE. However I've made fork (https://github.com/Chris-Prime/PureChatwhich does support this plugin. NOTE: chat-formatter must be set to false in order to allow PureChat format your chat instead."

**Comment by Kris-Driv** [comment]
@servantthought There should be config file inside FactionsPE folder. Just open it, find 'chat-format' and change 'true' to 'false'. Don't forget to save and restart your server. Console should log if it has chosen to use PureChat as chat formatter. Or if not, then FactionsPE itself will format chat messages. As far as I remember :rofl:

**Comment by Kris-Driv** [comment]
I guess solved?
