### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by artulloss** [BlockHorizons/FactionsPE#43]
Fatal error: Class 'pocketmine\event\TextContainer' not found in C:\Users\Adam\Desktop\stuff\pmmp\plugins\FactionsPE-reborn\src\localizer\Translatable.php on line 6

**Comment by artulloss** [comment]
solved, plugins is still way to broken for use

**Comment by Kris-Driv** [comment]
This plugin is fine for API version it was designed for. Haven't updated this plugin since my laptop broke. I'm now working to get new laptop so I hope that in one month I'll get new one and start fixing this project.
