### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iZeaoGamer** [BlockHorizons/FactionsPE#50]
Hey, whenever I disable chat formatter in the configurations, the plugin doesn't seem to work. Here's the error log:
ErrorException: "Undefined index: factions\engine\ChatEngine" (EXCEPTION) in "FactionsPE_dev-43.phar/src/factions/FactionsPE" at line 280
29.08 12:15:26 [Server] Server thread/DEBUG #0 FactionsPE_dev-43.phar/src/factions/FactionsPE(280): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined index: factions\engine\ChatEngine, string phar:///plugins/FactionsPE_dev-43.phar/src/factions/FactionsPE.php, integer 280, array Array())
29.08 12:15:26 [Server] Server thread/DEBUG #1 FactionsPE_dev-43.phar/src/factions/FactionsPE(151): factions\FactionsPE->loadIntegrations()
29.08 12:15:26 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginBase(102): factions\FactionsPE->onEnable()
29.08 12:15:26 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(611): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
29.08 12:15:26 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1931): pocketmine\plugin\PluginManager->enablePlugin(factions\FactionsPE object)
29.08 12:15:26 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1917): pocketmine\Server->enablePlugin(factions\FactionsPE object)
29.08 12:15:26 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1711): pocketmine\Server->enablePlugins(integer 1)
29.08 12:15:26 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
29.08 12:15:26 [Server] Server thread/DEBUG #8 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
29.08 12:15:26 [Server] Server thread/INFO Disabling FactionsPE v1.1.0

**Comment by Kris-Driv** [comment]
I changed the way Engines are stored. Now I use short class names instead of full patch ones.

**Comment by iZeaoGamer** [comment]
Thanks. By the way, you’ve done well on this plugin! Congratulations!

**Comment by Kris-Driv** [comment]
Thanks! I though that no one uses it until now :smile:
