### ISSUE TITLE
Some command issues

### ISSUE THREAD

**Issue by iZeaoGamer** [BlockHorizons/FactionsPE#51]
Hi, so I haven't tested this in full depth yet, but whenever I use certain commands, ex: /f perm list, it crashes the server. There are no main errors regarding this issue however, it's like as if I did /stop to stop the server, but instead, by using /f perm list basically somehow crashes the server without any errors given.
Here's what I mean, as an example:
iWin10PlayzMC joined the game [1/20]
29.08 15:55:23 [Server] Server thread/INFO TIP > You can subscribe to the founder of this server on youtube for: Great content, Server updates, Livestreams, and more! Subscribe to him today: http://tinyurl.com/sub2zeao
29.08 15:55:27 [Server] Server thread/INFO iWin10PlayzMC> /f perm
29.08 15:55:30 [Server] Server thread/INFO iWin10PlayzMC> /f perm list
29.08 15:55:31 [Multicraft] Server shut down (running)
29.08 15:55:31 [Multicraft] Restarting crashed server in 10 seconds
29.08 15:55:31 [Multicraft] Server stopped
29.08 15:55:31 [Disconnect] User iWin10PlayzMC[/82.38.148.87:65325] has disconnected, reason: Server shutting down
29.08 15:55:41 [Multicraft] Loading server properties
29.08 15:55:41 [Multicraft] Starting server!
29.08 15:55:41 [Multicraft] Loaded config for "@ Custom PHAR PHP 7.2 (For MCPE Servers - Place "custom-php7.2.phar" in base directory)"
29.08 15:55:41 [Multicraft] Updating eula.txt file
29.08 15:55:43 [Server] Server thread/INFO Loading pocketmine.yml...
29.08 15:55:43 [Server] Server thread/INFO Selected English (eng) as the base language
29.08 15:55:43 [Server] Server thread/INFO Loading server properties...
29.08 15:55:43 [Server] Server thread/INFO Starting Minecraft: PE server version v1.5.0
29.08 15:55:43 [Server] Server thread/NOTICE Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
29.08 15:55:43 [Server] Server thread/NOTICE To disable authentication, set "xbox-auth" to "false" in server.properties.
29.08 15:55:43 [Server] Server thread/INFO Opening server on 149.56.127.110:25655
29.08 15:55:43 [Server] Server thread/INFO This server is running PocketMine-MP version 3.1.4
29.08 15:55:43 [Server] Server thread/INFO PocketMine-MP is distributed under the LGPL License
29.08 15:55:43 [Server] Server thread/INFO Loading resource packs...
29.08 15:55:43 [Server] Server thread/ERROR Could not load plugin 'FactionsPE': Incompatible API version (plugin requires one of: 4.0.0)
29.08 15:55:43 [Server] Server thread/INFO Loading superBAR v2.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading AutoRestarter v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading PvPLevels v1.1.0
29.08 15:55:43 [Server] Server thread/INFO Loading SuperVanish v2.2
29.08 15:55:43 [Server] Server thread/INFO Loading Functions v2.0.1
29.08 15:55:43 [Server] Server thread/INFO Loading AWorldBorder v1.2
29.08 15:55:43 [Server] Server thread/INFO Loading EconomyAPI v5.7.2
29.08 15:55:43 [Server] Server thread/INFO Loading MultiWorld v1.5.0-beta2
29.08 15:55:43 [Server] Server thread/INFO Loading Bounty v2.1.0
29.08 15:55:43 [Server] Server thread/INFO Loading Wild v1.0.0-BETA
29.08 15:55:43 [Server] Server thread/INFO Loading Slapper v1.4.0
29.08 15:55:43 [Server] Server thread/INFO Loading PocketVote v2.1.3
29.08 15:55:43 [Server] Server thread/INFO Loading DevTools v1.13.0
29.08 15:55:43 [Server] Server thread/INFO Loading Festival v1.0.6-13-dev3
29.08 15:55:43 [Server] Server thread/INFO Loading TopVoter v3.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading WorldProtect v2.3.8
29.08 15:55:43 [Server] Server thread/INFO Loading BlazinFly v1.8.6
29.08 15:55:43 [Server] Server thread/INFO Loading CustomAlerts v2.1
29.08 15:55:43 [Server] Server thread/INFO Loading VMMPE-Action v1.0.0-BETA
29.08 15:55:43 [Server] Server thread/INFO VMPE Actions Plugin is now loading... Please wait for completion.
29.08 15:55:43 [Server] Server thread/INFO Loading SocialSpy v2.1.0
29.08 15:55:43 [Server] Server thread/INFO Loading Broadcaster v1.5
29.08 15:55:43 [Server] Server thread/INFO Loading ZipPluginLoader v1.2.1
29.08 15:55:43 [Server] Server thread/INFO Loading BankNotes v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading MysteryBox v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading Mystery Boxes from config...
29.08 15:55:43 [Server] Server thread/INFO Loading Mystery Box: Common Mystery Box
29.08 15:55:43 [Server] Server thread/INFO Loading Mystery Box: Vote Mystery Box
29.08 15:55:43 [Server] Server thread/INFO Loading Mystery Box: Uncommon Mystery Box
29.08 15:55:43 [Server] Server thread/INFO Loading Mystery Box: Mythic Mystery Box
29.08 15:55:43 [Server] Server thread/INFO Loading Mystery Box: Legendary Mystery Box
29.08 15:55:43 [Server] Server thread/INFO Loading FormAPI v1.2.0
29.08 15:55:43 [Server] Server thread/INFO Loading CustomDeaths v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading AutoClickerProtection v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading NameTag v1
29.08 15:55:43 [Server] Server thread/INFO Loading ClearLaggPE v2.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading PlayerVaults v2
29.08 15:55:43 [Server] Server thread/INFO Loading TeaSpoon v1.0.1
29.08 15:55:43 [Server] Server thread/INFO Loading Resources...
29.08 15:55:43 [Server] Server thread/INFO Loading PurePerms v1.4.2
29.08 15:55:43 [Server] Server thread/NOTICE PurePerms by 64FF00 & ProjectInfinity! #LEET.CC
29.08 15:55:43 [Server] INFO 888 888 .d8888b. d8888 8888888888 8888888888 .d8888b. .d8888b.
29.08 15:55:43 [Server] INFO 888 888 d88P Y88b d8P888 888 888 d88P Y88b d88P Y88b
29.08 15:55:43 [Server] INFO 888888888888 888 d8P 888 888 888 888 888 888 888
29.08 15:55:43 [Server] INFO 888 888 888d888b. d8P 888 8888888 8888888 888 888 888 888
29.08 15:55:43 [Server] INFO 888 888 888P "Y88b d88 888 888 888 888 888 888 888
29.08 15:55:43 [Server] INFO 888888888888 888 888 8888888888 888 888 888 888 888 888
29.08 15:55:43 [Server] INFO 888 888 Y88b d88P 888 888 888 Y88b d88P Y88b d88P
29.08 15:55:43 [Server] INFO 888 888 "Y8888P" 888 888 888 "Y8888P" "Y8888P"
29.08 15:55:43 [Server] Server thread/INFO Setting default language to 'en'
29.08 15:55:43 [Server] Server thread/NOTICE Multiworld support is currently disabled.
29.08 15:55:43 [Server] Server thread/NOTICE Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
29.08 15:55:43 [Server] Server thread/INFO Loading ChatScrambler v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading AutoClearLagg v2.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading BossBar v1.0.15
29.08 15:55:43 [Server] Server thread/INFO Loading AllAPILoader v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Enabling DevTools v1.13.0
29.08 15:55:43 [Server] Server thread/ERROR Could not load plugin 'BankNotes': plugin exists
29.08 15:55:43 [Server] Server thread/INFO Loading PiggyCustomEnchantsShop v1.1.0
29.08 15:55:43 [Server] Server thread/INFO Loading Sell v1.3.0
29.08 15:55:43 [Server] Server thread/INFO Plugin Loading!
29.08 15:55:43 [Server] Server thread/INFO Loading WolfGangShopUI v4
29.08 15:55:43 [Server] Server thread/INFO Loading EssentialsPE v2.1.0
29.08 15:55:43 [Server] Server thread/INFO Loading InventoryMonitor v1.3.2
29.08 15:55:43 [Server] Server thread/INFO Loading AliasReborn v1.0.2-3.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading StaffChat v1.1.1
29.08 15:55:43 [Server] Server thread/INFO Loading Repair v1.0.2
29.08 15:55:43 [Server] Server thread/INFO Loading KitUI v1.3.0
29.08 15:55:43 [Server] Server thread/INFO Loading JoinCommands v2.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading BanItem v2.3.3
29.08 15:55:43 [Server] Server thread/INFO Loading PiggyCustomEnchants v1.2.0
29.08 15:55:43 [Server] Server thread/INFO Loading MSpawns v2.2
29.08 15:55:43 [Server] Server thread/INFO Loading CommandBlocker v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading VMCore v1.0.0-BETA
29.08 15:55:43 [Server] Server thread/INFO Loading CombatLogger v0.0.6
29.08 15:55:43 [Server] Server thread/INFO Loading GappleCooldown v1.1.0
29.08 15:55:43 [Server] Server thread/INFO Loading ItemID v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading AFantasyStopTransfer v0.2
29.08 15:55:43 [Server] Server thread/INFO Loading VotePoints v1.5.3
29.08 15:55:43 [Server] Server thread/INFO Loading MOTDShuffle v1.1.7
29.08 15:55:43 [Server] Server thread/INFO Loading PureChat v1.4.6
29.08 15:55:43 [Server] Server thread/INFO Registered folder plugin loader
29.08 15:55:43 [Server] Server thread/INFO Enabling WorldProtect v2.3.8
29.08 15:55:43 [Server] Server thread/INFO Enabled 4 features
29.08 15:55:43 [Server] Server thread/INFO Enabling CustomAlerts v2.1
29.08 15:55:43 [Server] Server thread/INFO Enabling Broadcaster v1.5
29.08 15:55:43 [Server] Server thread/INFO Enabling ZipPluginLoader v1.2.1
29.08 15:55:43 [Server] Server thread/INFO Enabling TeaSpoon v1.0.1
29.08 15:55:43 [Server] Server thread/INFO Loading...
29.08 15:55:43 [Server] INFO MMP""MM""YMM .M"""bgd
29.08 15:55:43 [Server] INFO P' MM `7 ,MI "Y
29.08 15:55:43 [Server] INFO MM .gP"Ya ,6"Yb. `MMb. `7MMpdMAo. ,pW"Wq. ,pW"Wq.`7MMpMMMb.
29.08 15:55:43 [Server] INFO MM ,M' Yb 8) MM `YMMNq. MM `Wb 6W' `Wb 6W' `Wb MM MM
29.08 15:55:43 [Server] INFO MM 8M"""""" ,pm9MM . `MM MM M8 8M M8 8M M8 MM MM
29.08 15:55:43 [Server] INFO MM YM. , 8M MM Mb dM MM ,AP YA. ,A9 YA. ,A9 MM MM
29.08 15:55:43 [Server] INFO .JMML.`Mbmmd' `Moo9^Yo.P"Ybmmd" MMbmmd' `Ybmd9' `Ybmd9'.JMML JMML.
29.08 15:55:43 [Server] INFO MM
29.08 15:55:43 [Server] INFO .JMML. Stew and rum is often pregnant.
29.08 15:55:43 [Server] INFO Copyright (C) CortexPE 2017-2018
29.08 15:55:43 [Server] Server thread/INFO TeaSpoon is distributed under the AGPL License
29.08 15:55:43 [Server] Server thread/INFO Enabling BossBar v1.0.15
29.08 15:55:43 [Server] Server thread/INFO Enabling AllAPILoader v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Loading FactionsPE v1.1.0
29.08 15:55:43 [Server] Server thread/INFO Enabling MSpawns v2.2
29.08 15:55:43 [Server] Server thread/INFO Enabling MOTDShuffle v1.1.7
29.08 15:55:43 [Server] Server thread/INFO has been activated!
29.08 15:55:43 [Server] Server thread/INFO Preparing level "world"
29.08 15:55:43 [Server] Server thread/INFO Preparing level "teanether"
29.08 15:55:43 [Server] Server thread/INFO Preparing level "teaender"
29.08 15:55:43 [Server] Server thread/INFO Enabling superBAR v2.0.0
29.08 15:55:43 [Server] Server thread/INFO superBAR will be enabled after the complete server load
29.08 15:55:43 [Server] Server thread/INFO Enabling AutoRestarter v1.0.0
29.08 15:55:43 [Server] Server thread/INFO Enabling PvPLevels v1.1.0
29.08 15:55:43 [Server] Server thread/NOTICE 11 levels loaded!
29.08 15:55:43 [Server] Server thread/NOTICE 3 floating texts loaded!
29.08 15:55:43 [Server] Server thread/INFO Enabling SuperVanish v2.2
29.08 15:55:43 [Server] Server thread/INFO Enabling Functions v2.0.1
29.08 15:55:43 [Server] Server thread/INFO Plugin Enabled.
29.08 15:55:43 [Server] Server thread/INFO Enabling AWorldBorder v1.2
29.08 15:55:43 [Server] Server thread/INFO Enabled !
29.08 15:55:43 [Server] Server thread/INFO Enabling EconomyAPI v5.7.2
29.08 15:55:44 [Server] Server thread/NOTICE Database provider was set to: Yaml
29.08 15:55:44 [Server] Server thread/INFO Enabling MultiWorld v1.5.0-beta2
29.08 15:55:44 [Server] Server thread/NOTICE Old config found, updating config...
29.08 15:55:44 [Server] Server thread/INFO Enabling Bounty v2.1.0
29.08 15:55:44 [Server] Server thread/INFO Loaded Bounty plugin succesfully.
29.08 15:55:44 [Server] Server thread/INFO Enabling Wild v1.0.0-BETA
29.08 15:55:44 [Server] Server thread/INFO Wild enabled!
29.08 15:55:44 [Server] Server thread/INFO Enabling Slapper v1.4.0
29.08 15:55:44 [Server] Server thread/INFO Enabling PocketVote v2.1.3
29.08 15:55:44 [Server] Server thread/INFO Enabling Festival v1.0.6-13-dev3
29.08 15:55:44 [Server] Server thread/INFO by -----------.------------
29.08 15:55:44 [Server] Server thread/INFO ,-. ,-. ,-. |-. ,-. . .
29.08 15:55:44 [Server] Server thread/INFO | | |-' | | | | | | | |
29.08 15:55:44 [Server] Server thread/INFO `-| `-' ' ' `-' `-' `-|
29.08 15:55:44 [Server] Server thread/INFO ,| /|
29.08 15:55:44 [Server] Server thread/INFO `' `-'
29.08 15:55:44 [Server] Server thread/INFO 0 commands in 17 areas
29.08 15:55:44 [Server] Server thread/INFO Enabling TopVoter v3.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling BlazinFly v1.8.6
29.08 15:55:44 [Server] Server thread/INFO BlazinFly v1.8.6 by iiFlamiinBlaze enabled
29.08 15:55:44 [Server] Server thread/INFO Enabling VMMPE-Action v1.0.0-BETA
29.08 15:55:44 [Server] Server thread/INFO VMPE Actions plugin is now enabled. As far as we know, there's no errors on-enable.
29.08 15:55:44 [Server] Server thread/INFO Enabling SocialSpy v2.1.0
29.08 15:55:44 [Server] Server thread/INFO Social spy has been enabled. Let the magic begin. >:D
29.08 15:55:44 [Server] Server thread/INFO Enabling BankNotes v1.0.0
29.08 15:55:44 [Server] Server thread/INFO enabled!
29.08 15:55:44 [Server] Server thread/INFO Enabling MysteryBox v1.0.0
29.08 15:55:44 [Server] Server thread/INFO All configuration seems to be fine, system has been enabled
29.08 15:55:44 [Server] Server thread/INFO Enabling FormAPI v1.2.0
29.08 15:55:44 [Server] Server thread/INFO Enabling CustomDeaths v1.0.0
29.08 15:55:44 [Server] Server thread/INFO Version: 1.0.0 for API: 3.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling AutoClickerProtection v1.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabled.
29.08 15:55:44 [Server] Server thread/INFO Enabling NameTag v1
29.08 15:55:44 [Server] Server thread/INFO Enabling ClearLaggPE v2.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling PlayerVaults v2
29.08 15:55:44 [Server] Server thread/INFO Registered InvMenuHandler
29.08 15:55:44 [Server] Server thread/INFO Enabling PurePerms v1.4.2
29.08 15:55:44 [Server] Server thread/NOTICE Set data provider to YAMLv1.
29.08 15:55:44 [Server] Server thread/INFO Enabling ChatScrambler v1.0.0
29.08 15:55:44 [Server] Server thread/INFO Version: 1.0.0 for API: 3.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling AutoClearLagg v2.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling PiggyCustomEnchantsShop v1.1.0
29.08 15:55:44 [Server] Server thread/INFO Enabled.
29.08 15:55:44 [Server] Server thread/INFO Enabling Sell v1.3.0
29.08 15:55:44 [Server] INFO _____ _ _
29.08 15:55:44 [Server] INFO / ____| | | |
29.08 15:55:44 [Server] INFO | (___ ___| | |
29.08 15:55:44 [Server] INFO \___ \ / _ \ | |
29.08 15:55:44 [Server] INFO ____) | __/ | |
29.08 15:55:44 [Server] INFO |_____/ \___|_|_|
29.08 15:55:44 [Server] INFO Enabled Sell by Muqsit and JackMD.
29.08 15:55:44 [Server] Server thread/INFO Enabling WolfGangShopUI v4
29.08 15:55:44 [Server] Server thread/INFO WolfGangShopUI is finally enabled!
29.08 15:55:44 [Server] Server thread/INFO Enabling EssentialsPE v2.1.0
29.08 15:55:44 [Server] Server thread/INFO Preparing level "end"
29.08 15:55:44 [Server] Server thread/INFO Preparing level "nether"
29.08 15:55:44 [Server] Server thread/INFO Enabling InventoryMonitor v1.3.2
29.08 15:55:44 [Server] Server thread/INFO Selected English (eng) as the base language
29.08 15:55:44 [Server] Server thread/INFO Enabling AliasReborn v1.0.2-3.0.0
29.08 15:55:44 [Server] Server thread/INFO Version: 1.0.2 for API: 3.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling StaffChat v1.1.1
29.08 15:55:44 [Server] Server thread/INFO Enabling Repair v1.0.2
29.08 15:55:44 [Server] Server thread/INFO Plugin Enabled.
29.08 15:55:44 [Server] Server thread/INFO Enabling KitUI v1.3.0
29.08 15:55:44 [Server] Server thread/NOTICE Enabled! - By Infernus101
29.08 15:55:44 [Server] Server thread/INFO Using PiggyCustomEnchants!
29.08 15:55:44 [Server] Server thread/INFO Enabling JoinCommands v2.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling BanItem v2.3.3
29.08 15:55:44 [Server] Server thread/INFO Enabling PiggyCustomEnchants v1.2.0
29.08 15:55:44 [Server] Server thread/INFO Enabled.
29.08 15:55:44 [Server] Server thread/INFO Enabling CommandBlocker v1.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling VMCore v1.0.0-BETA
29.08 15:55:44 [Server] Server thread/INFO Enabling CombatLogger v0.0.6
29.08 15:55:44 [Server] Server thread/INFO Enabling GappleCooldown v1.1.0
29.08 15:55:44 [Server] Server thread/INFO GappleCooldown by CaptainDuck enabled!
29.08 15:55:44 [Server] Server thread/INFO Enabling ItemID v1.0.0
29.08 15:55:44 [Server] Server thread/INFO Enabling AFantasyStopTransfer v0.2
29.08 15:55:44 [Server] Server thread/NOTICE FantasyStopTransfer by Enrick3344 Enabled!
29.08 15:55:44 [Server] Server thread/NOTICE Transfer is set to true! Players will be transfered to play.voidfactionspe.ml;25655 on server stop.
29.08 15:55:44 [Server] Server thread/INFO Enabling VotePoints v1.5.3
29.08 15:55:44 [Server] Server thread/INFO Guest : 0
29.08 15:55:44 [Server] Server thread/INFO Voter : 5
29.08 15:55:44 [Server] Server thread/INFO BetterVoter : 10
29.08 15:55:44 [Server] Server thread/INFO 20Votes : 20
29.08 15:55:44 [Server] Server thread/INFO 30Votes : 30
29.08 15:55:44 [Server] Server thread/INFO 60Votes : 60
29.08 15:55:44 [Server] Server thread/INFO Enabling PureChat v1.4.6
29.08 15:55:44 [Server] Server thread/NOTICE FactionsPE support enabled
29.08 15:55:44 [Server] Server thread/INFO Enabling FactionsPE v1.1.0
29.08 15:55:44 [Server] Server thread/INFO Enabling... version [PHOENIX]
29.08 15:55:44 [Server] Server thread/INFO Data provider: YAML
29.08 15:55:44 [Server] Server thread/INFO 5 faction(s) were loaded
29.08 15:55:44 [Server] Server thread/INFO Economy provider: EconomyAPI
29.08 15:55:44 [Server] Server thread/INFO Chat formatter: PureChat
29.08 15:55:44 [Server] Server thread/INFO Power regeneration enabled
29.08 15:55:44 [Server] Server thread/INFO Built-In HUD enabled
29.08 15:55:44 [Server] Server thread/INFO Enabled
29.08 15:55:44 [Server] Server thread/INFO Starting GS4 status listener
29.08 15:55:44 [Server] Server thread/INFO Setting query port to 25655
29.08 15:55:44 [Server] Server thread/INFO Query running on 149.56.127.110:25655
29.08 15:55:44 [Server] Server thread/INFO Default game type: Survival Mode
29.08 15:55:44 [Server] Startup Done (1.251s)! For help, type "help" or "?"
29.08 15:55:44 [Server] Server thread/INFO TIP > You can subscribe to the founder of this server on youtube for: Great content, Server updates, Livestreams, and more! Subscribe to him today: http://tinyurl.com/sub2zeao
29.08 15:55:44 [Server] Server thread/INFO [superBAR] superBAR loading...
29.08 15:55:44 [Server] Server thread/INFO [superBAR] EconomyAPI OK!
29.08 15:55:44 [Server] Server thread/INFO [superBAR] PurePerms OK!
29.08 15:55:44 [Server] Server thread/INFO [superBAR] superBAR by FaigerSYS enabled!
29.08 15:55:44 [Server] Server thread/INFO The server will reboot in 60 mins
Keep in mind - I have socialspy plugin to fully test this, as you can see with me using a command: /f perm list, and the server freezes, and crashes the server. I'm not entirely sure why it's causing this issue, but I can also see it happens to other commands as well. If you need anymore things to reproduce this issue, I can make a video regarding this, and show you what it does, step by step.
Another way of crashing the server with this plugin, is if you have a faction, and do /f leave, you can leave the faction (Your own faction), and when you do /f disband, it crashes the server. Those issues are the only way of crashing the server, leading this to be a bug, and can possibly be abused by players. I believe the reason of the second issue, is because if you /f leave, it still recognises that you're still in that faction, and when you disband it, it leads to complications, and possible crashes, thus meaning the world cannot be saved due to this. Also, when the server comes back up, it still says you're in a faction (used previously), as if I never left the faction, or as if the world or server never saved. My solution to the /f leave, is to only make that for Faction members only, not faction leaders. As that could fix this issue. And with /f perm list, I'm not sure why it crashes when executed. I hope you can try and fix this. Thank you, in advanced.

**Comment by Kris-Driv** [comment]
Fixed. Big thanks for reporting this. If you found any other unexpected shutdowns please open issue. I appreciate your help :)
