### ISSUE TITLE
Faction Safezone and warzone

### ISSUE THREAD

**Issue by Croc3ll** [BlockHorizons/FactionsPE#57]
Safezone and warzone are unable to be joined it says joined but than says unknown error

**Comment by Kris-Driv** [comment]
Thanks for reporting. I'll fix that asap.

**Comment by Croc3ll** [comment]
Might have been my bad on my part because I wasn't in a faction at the time but i got around this by giving myself power and a test factions and doing /f claim s 20 warzone maybe it's a bug i'm not sure

**Comment by Kris-Driv** [comment]
I fixed. You can no longer join special factions.
