### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xDanub** [BlockHorizons/FactionsPE#60]
thread/CRITICAL Unhandled exception executing command 'f info' in faction: undefined flag 'inf_power'
22.10 13:44:22 [Server] Server thread/CRITICAL Exception: "undefined flag 'inf_power'" (EXCEPTION) in "FactionsPE-reborn/src/factions/entity/Faction" at line 200

**Comment by xDanub** [comment]
Please help asap! Server is running and some reason factions broke!

**Comment by Kris-Driv** [comment]
I have no idea how you caused this problem. Try deleting ``flags.yml`` in ``plugin_data/FactionsPE`` folder.

**Comment by xDanub** [comment]
thread/CRITICAL Unhandled exception executing command 'f create pvp' in faction: undefined flag 'permanent'
24.10 03:27:32 [Server] Server thread/CRITICAL Exception: "undefined flag 'permanent'" (EXCEPTION) in "FactionsPE-

This is even after i deleted all files for both factionspe and your fork of purechat...

**Comment by DaWOLFEE** [comment]
Sup Danub XD

> thread/CRITICAL Unhandled exception executing command 'f create pvp' in faction: undefined flag 'permanent'
> 24.10 03:27:32 [Server] Server thread/CRITICAL Exception: "undefined flag 'permanent'" (EXCEPTION) in "FactionsPE-
> 
> This is even after i deleted all files for both factionspe and your fork of purechat...

I thought Stryde ran FactionsPro...
