### ISSUE TITLE
Direct Download

### ISSUE THREAD

**Issue by DaWOLFEE** [BlockHorizons/FactionsPE#62]
I apologize deeply for opening and issue for this, but can you link me to a direct download to the .phar file for Chris-Prime's PureChat fork. As when I download it off of github, there is no .phar file to install. Thanks.

**Comment by Kris-Driv** [comment]
Find a way to compile, or run plugin from source using DevTools.

**Comment by teorailin** [comment]
https://poggit.pmmp.io/ci/BlockHorizons/FactionsPE
you can see the link in the wiki ;D

**Comment by Kris-Driv** [comment]
@teorailin forgot about that. But, anyway this project is not maintained anymore, so don't bother :/
