### ISSUE TITLE
PureChat issue

### ISSUE THREAD

**Issue by RvmblinQ** [BlockHorizons/FactionsPE#69]
I love this plugin I think it's the perfect Factions plugins for Pocket Edition however, there seems to be an issue with the PureChat.

When running the FactionsPE plugin on its own everything works as it should, but when I went to type something in chat I discovered the plugins own chat format. I didn't like it because I wanted to have my own ranks alongside the faction name (e.g {faction} Owner {playersname}). I saw that I already had the PureChat plugin installed and running, but it wasn't picking it up. So I went in and read through the details of the plugin and found that we have to download a custom PureChat plugin, which I did... Now when I run both the PureChat and FactionsPE plugins together, they both stop working:

[22:27:12] [Server thread/CRITICAL]: Could not load plugin 'FactionsPE': Circular dependency detected
[22:27:12] [Server thread/CRITICAL]: Could not load plugin 'PureChat': Circular dependency detected

I then tried to fix it myself by going to the PureChat config and changed the default factions plugin (default-factions-plugin: FactionsPE). I also went into the FactionsPE config and changed the chat formatter to false (chat-formatter: false). The same CRITICAL message shows up in the log/console so I came to here looking for an answer.

**Comment by KiraGodx** [comment]
@RvmblinQ Did you ever figure out what the problem was?

**Comment by Kris-Driv** [comment]
PocketMine changed how dependencies work. The fix would be to remove dependency from plugin.yml, from either of plugins.
