### ISSUE TITLE
How to i use pure chat support.

### ISSUE THREAD

**Issue by xXSirGamesXx** [BlockHorizons/FactionsPE#7]
I saw this on the TODO, but I would like to know how to add faction names to pre chat. This plugin is already great, once the todo is finished it'll be even better. But if someone could tell me how to do this that would be great :P

**Comment by Kris-Driv** [comment]
Use this PureChat: https://github.com/Chris-Prime/PureChat

Edit the config for FactionsPE, set chat-formatter to false. Then ope PureChat config and set faction-plugin to FactionsPE

**Comment by xXSirGamesXx** [comment]
Ok thanks worked.
