### ISSUE TITLE
problem at lign 293

### ISSUE THREAD

**Issue by Azaroth90340** [BlockHorizons/FactionsPE#70]
hello,

I have a small problem on your plugin, when I put true the line chat-formatter, in the config.yml, it tells me that I have an error, on line 293 in src / factions / factionPE, here is the line: $ pc-> loadFactionsPlugin ();

Could you find a solution to my problem, thanks in advance

**Comment by samupozzo** [comment]
Show all the error message

**Comment by Kenshiroxxe** [comment]
[Server thread/CRITICAL]: Error: "Call to private method _64FF00\PureChat\PureChat::loadFactionsPlugin() from context 'factions\FactionsPE'" (EXCEPTION) in "plugins/FactionsPE.phar/src/factions/FactionsPE" at line 293

**Comment by thecouchyeti** [comment]
Was this resolved because you need read the wiki. It says exactly how to enable purechat.
