### ISSUE TITLE
Error with claiming

### ISSUE THREAD

**Issue by BlobKing21** [BlockHorizons/FactionsPE#72]
I may just be stupid, but I installed this plugin, restarted my server, and created a faction. All was going well, except for when I went to claim some land, All that happened was a message that said, "Land claiming not enabled on Factions" (Factions is the name of the world). I'd love to show some errors, but this is all I get. If it's just something in config that I need to change to true then please let me know. Thanks in advance!

Also an error with ClaimAuto.php on line 61, something about getName()

**Comment by RubyTemple** [comment]
send the error

**Comment by Kris-Driv** [comment]
Little too late, but yea, you must define in which worlds claiming is enabled.
