### ISSUE TITLE
Claim Warzone and SafeZone

### ISSUE THREAD

**Issue by Kenshiroxxe** [BlockHorizons/FactionsPE#74]
Im French and I would like create my minecraft server (pvp/faction) but i'm new to plugin creation and configuration.
I would like to know, how we claim chunk with warzone and safezone ?

**Comment by Kris-Driv** [comment]
This video explains it nicely. Although it's recorded on java version, this plugin has same commands, and functionality.
https://www.youtube.com/watch?v=XNICXhY0myc
