### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by minijaham** [BlockHorizons/FactionsPE#77]
31.03 00:05:00 [Server] Server thread/CRITICAL ErrorException: "Undefined variable: fplayer" (EXCEPTION) in "plugins/FactionsPE.phar/src/factions/engine/MainEngine" at line 148
31.03 00:05:00 [Server] Server thread/DEBUG #0 plugins/FactionsPE.phar/src/factions/engine/MainEngine(148): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[27] Undefined variable: fplayer, string[112] phar:///plugins/FactionsPE.phar/sr, integer 148, array[2])
31.03 00:05:00 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(42): factions\engine\MainEngine->showMotdOnJoin(object pocketmine\event\player\PlayerJoinEvent)
31.03 00:05:00 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object factions\engine\MainEngine, object pocketmine\event\player\PlayerJoinEvent)
31.03 00:05:00 [Server] Server thread/DEBUG #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent)
31.03 00:05:00 [Server] Server thread/DEBUG #4 src/pocketmine/Player(1045): pocketmine\event\Event->call()
31.03 00:05:00 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(315): pocketmine\Player->doFirstSpawn()
31.03 00:05:00 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/SetLocalPlayerAsInitializedPacket(45): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)
31.03 00:05:00 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
31.03 00:05:00 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)
31.03 00:05:00 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
31.03 00:05:00 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3096): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
31.03 00:05:00 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
31.03 00:05:00 [Server] Server thread/DEBUG #12 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 68.7.150.203 56808, object raklib\protocol\EncapsulatedPacket, integer 0)
31.03 00:05:00 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
31.03 00:05:00 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
31.03 00:05:00 [Server] Server thread/DEBUG #15 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
31.03 00:05:00 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
31.03 00:05:00 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1585613100.5798)
31.03 00:05:00 [Server] Server thread/DEBUG #18 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
31.03 00:05:00 [Server] Server thread/DEBUG #19 src/pocketmine/Server(1584): pocketmine\Server->start()
31.03 00:05:00 [Server] Server thread/DEBUG #20 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
31.03 00:05:00 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(296): pocketmine\server()
31.03 00:05:00 [Server] Server thread/DEBUG #22 (11): require(string[107] phar:///PMMP-Latest-Stable.phar/sr)

**Comment by Kris-Driv** [comment]
This error has been fixed. Thanks for reporting!
