### ISSUE TITLE
Factions not saving issue

### ISSUE THREAD

**Issue by xXSirGamesXx** [BlockHorizons/FactionsPE#8]
How do I make factions save? Whenever I create a faction its fine, but when server restarts it deletes. There's no files in the factions folder if its supposed to save there.
`[07:14:37] [Server thread/INFO]: Enabling FactionsPE v0.9.8.6
[07:14:37] [Server thread/INFO]: [FactionsPE] Enabling...
[07:14:37] [Server thread/INFO]: [FactionsPE] Data provider: YAML
[07:14:37] [Server thread/INFO]: [FactionsPE] 3 faction(s) were loaded
[07:14:37] [Server thread/INFO]: [FactionsPE] Power regeneration enabled
[07:14:37] [Server thread/INFO]: [FactionsPE] Built-In HUD enabled
[07:14:37] [Server thread/INFO]: [FactionsPE] Enabled
[07:14:37] [Server thread/INFO]: Enabling PureChat v1.4`
I also turned deleting inactive factions off.

**Comment by xXSirGamesXx** [comment]
Is there any fix? I really need this plugin to work.

**Comment by Kris-Driv** [comment]
Any errors or whatever?

**Comment by xXSirGamesXx** [comment]
No errors. Just when server restarts after a player creates a faction they aren't in the faction anymore. Also nothing saves in the factions folder either.

**Comment by Kris-Driv** [comment]
Give me sometime. I'll fix the issue tomorrow

**Comment by xXSirGamesXx** [comment]
ok thanks :)

**Comment by xXSirGamesXx** [comment]
Also @Chris-Prime i dont know if there is something wrong with flags.yml and permissions.yml but there's nothing there. Was wondering if there is a way to use that too

**Comment by dries-c** [comment]
fixed yet?

**Comment by xXSirGamesXx** [comment]
@Chris-Prime its been a pretty long time, any progress?

**Comment by xXSirGamesXx** [comment]
I might be able to fix this actually. The current way to save is to /f create, /f claim, /f sethome. Need to `$this->save();` after we create the faction

**Comment by xXSirGamesXx** [comment]
@Chris-Prime We could use your help :)

**Comment by xXSirGamesXx** [comment]
Merge my PR

**Comment by Sandertv** [comment]
I'll see if I can find some time to fix this.

**Comment by xXSirGamesXx** [comment]
ok thanks.

**Comment by Kris-Driv** [comment]
Not into coding anymore. MCPE deleted, computer in the trash bin and no time at all. Don't count on my :(

**Comment by Kris-Driv** [comment]
Little off-topic, but who cares - You can follow me on Instagram to see what I'm doing instead of this @flipkris :D

**Comment by Kris-Driv** [comment]
I can not reproduce this issue in any manner.
