### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by jorgemejia25** [BlockHorizons/FactionsPE#82]
Fatal error: Declaration of dominate\Command::addParameter(dominate\parameter\Parameter $arg) must be compatible with pocketmine\command\Command::addParameter(pocketmine\network\mcpe\protocol\types\CommandParameter $parameter, int $overloadIndex = 0): void in phar:///home/container/plugins/FactionsPE.phar/src/dominate/Command.php on line 31
23:11:00 Server|EMERGENCY > An unrecoverable error has occurred and the server has crashed. Creating a crash dump
23:11:00 Server|EMERGENCY > Please upload the "/home/container/crashdumps/Wed_Aug_19-23.11.00-UTC_2020.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Kris-Driv** [comment]
This is outdated and not maintained.
