### ISSUE TITLE
To fix really fast because its very important lol

### ISSUE THREAD

**Issue by DumnezeuBriceag** [BlockHorizons/FactionsPE#84]
Fatal error: Declaration of dominate\Command::addParameter(dominate\parameter\Parameter $arg) must be compatible with pocketmine\command\Command::addParameter(pocketmine\network\mcpe\protocol\types\CommandParameter $parameter, int $overloadIndex = 0): void in phar:///home/container/plugins/FactionsPE_dev-72 (1).phar/src/dominate/Command.php on line 31
15:07:30 Server|EMERGENCY > An unrecoverable error has occurred and the server has crashed. Creating a crash dump
15:07:30 Server|EMERGENCY > Please upload the "/home/container/crashdumps/Sun_Sep_27-15.07.30-UTC_2020.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

just fix, I can't use the plugin and I seen many people with this problem so please hurry, thanks.

**Comment by Kris-Driv** [comment]
What version of PocketMine-MP are you using?
