### ISSUE TITLE
The PureChat thing is not working, I tried even to open from source but yeah

### ISSUE THREAD

**Issue by DumnezeuBriceag** [BlockHorizons/FactionsPE#85]
literally what the title says, any fix?

**Comment by Kris-Driv** [comment]
I dropped the support for PureChat. Didn't even plan to update it because of how dead this project is. If you really need it, let me know!

Cheers!

**Comment by Kris-Driv** [comment]
Everything is fixed, and PureChat is now updated. Check Readme.
