### ISSUE TITLE
Why i cant hit people

### ISSUE THREAD

**Issue by ItzFel** [BlockHorizons/FactionsPE#86]

**Comment by Kris-Driv** [comment]
Is there any error output? Maybe a message? I'll test it myself, it probably has something to do with default settings

**Comment by Kris-Driv** [comment]
Thank you for reporting! The issue has been fixed by incoming commit. Here is the fixed .phar file: https://poggit.pmmp.io/r/111806/FactionsPE_dev-84.phar
