### ISSUE TITLE
ChatEngine

### ISSUE THREAD

**Issue by KareemDoezMc** [BlockHorizons/FactionsPE#92]
01.01 06:26:52 [Server] Server thread/CRITICAL TypeError: "Incorrect type of element at "1": Argument 1 passed to pocketmine\event\player\PlayerChatEvent::pocketmine\event\player\{closure}() must implement interface pocketmine\command\CommandSender, instance of fpe\entity\FConsole given, called in phar:///pocketmine/jar/pocketmine.phar/src/pocketmine/utils/Utils.php on line 706" (EXCEPTION) in "pmsrc/src/pocketmine/utils/Utils" at line 708
01.01 06:26:52 [Server] Server thread/CRITICAL #0 pmsrc/src/pocketmine/event/player/PlayerChatEvent(101): pocketmine\utils\Utils::validateArrayValueType(array[2], object Closure)
01.01 06:26:52 [Server] Server thread/CRITICAL #1 plugins/FactionsPE_v1.3.0.phar/src/fpe/engine/ChatEngine(55): pocketmine\event\player\PlayerChatEvent->setRecipients(array[2])
01.01 06:26:52 [Server] Server thread/CRITICAL #2 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): fpe\engine\ChatEngine->onChat(object pocketmine\event\player\PlayerChatEvent)
01.01 06:26:52 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object fpe\engine\ChatEngine, object pocketmine\event\player\PlayerChatEvent)
01.01 06:26:52 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerChatEvent)
01.01 06:26:52 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/Player(2326): pocketmine\event\Event->call()
01.01 06:26:52 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(130): pocketmine\Player->chat(string[2] ok)
01.01 06:26:52 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/network/mcpe/protocol/TextPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleText(object pocketmine\network\mcpe\protocol\TextPacket)
01.01 06:26:52 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\TextPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
01.01 06:26:52 [Server] Server thread/CRITICAL #9 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\TextPacket)
01.01 06:26:52 [Server] Server thread/CRITICAL #10 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
01.01 06:26:52 [Server] Server thread/CRITICAL #11 pmsrc/src/pocketmine/Player(3273): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
01.01 06:26:52 [Server] Server thread/CRITICAL #12 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
01.01 06:26:52 [Server] Server thread/CRITICAL #13 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 73.196.42.2 53713, object raklib\protocol\EncapsulatedPacket, integer 0)
01.01 06:26:52 [Server] Server thread/CRITICAL #14 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
01.01 06:26:52 [Server] Server thread/CRITICAL #15 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
01.01 06:26:52 [Server] Server thread/CRITICAL #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
01.01 06:26:52 [Server] Server thread/CRITICAL #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
01.01 06:26:52 [Server] Server thread/CRITICAL #18 pmsrc/src/pocketmine/Server(2156): pocketmine\snooze\SleeperHandler->sleepUntil(double 1609500412.7701)
01.01 06:26:52 [Server] Server thread/CRITICAL #19 pmsrc/src/pocketmine/Server(1993): pocketmine\Server->tickProcessor()
01.01 06:26:52 [Server] Server thread/CRITICAL #20 pmsrc/src/pocketmine/Server(1587): pocketmine\Server->start()
01.01 06:26:52 [Server] Server thread/CRITICAL #21 pmsrc/src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[59] /pocketmine/, string[67] /pocketmine/plugins/)
01.01 06:26:52 [Server] Server thread/CRITICAL #22 pmsrc/src/pocketmine/PocketMine(302): pocketmine\server()
01.01 06:26:52 [Server] Server thread/CRITICAL #23 pmsrc(11): require(string[115] phar:///pocketmine/jar/pocketmine)
01.01 06:26:52 [Server] Server thread/CRITICAL Previous: TypeError: "Argument 1 passed to pocketmine\event\player\PlayerChatEvent::pocketmine\event\player\{closure}() must implement interface pocketmine\command\CommandSender, instance of fpe\entity\FConsole given, called in phar:///pocketmine/jar/pocketmine.phar/src/pocketmine/utils/Utils.php on line 706" (EXCEPTION) in "pmsrc/src/pocketmine/event/player/PlayerChatEvent" at line 101
01.01 06:26:52 [Server] Server thread/CRITICAL #0 pmsrc/src/pocketmine/utils/Utils(706): pocketmine\event\player\PlayerChatEvent->pocketmine\event\player\{closure}(object fpe\entity\FConsole)
01.01 06:26:52 [Server] Server thread/CRITICAL #1 pmsrc/src/pocketmine/event/player/PlayerChatEvent(101): pocketmine\utils\Utils::validateArrayValueType(array[2], object Closure)
01.01 06:26:52 [Server] Server thread/CRITICAL #2 plugins/FactionsPE_v1.3.0.phar/src/fpe/engine/ChatEngine(55): pocketmine\event\player\PlayerChatEvent->setRecipients(array[2])
01.01 06:26:52 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): fpe\engine\ChatEngine->onChat(object pocketmine\event\player\PlayerChatEvent)

**Comment by Kris-Driv** [comment]
Thanks for reporting. I'll fix it today.

**Comment by Kris-Driv** [comment]
Fixed.
