### ISSUE TITLE
Error #2

### ISSUE THREAD

**Issue by KareemDoezMc** [BlockHorizons/FactionsPE#93]
01.01 06:28:37 [Server] Server thread/CRITICAL ErrorException: "Trying to get property 'x' of non-object" (EXCEPTION) in "plugins/FactionsPE_v1.3.0.phar/src/fpe/utils/Collections" at line 70
01.01 06:28:37 [Server] Server thread/CRITICAL #0 plugins/FactionsPE_v1.3.0.phar/src/fpe/utils/Collections(70): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[40] Trying to get property 'x' of non-object, string[126] phar:///pocketmine/plugins/Factio, integer 70, array[24])
01.01 06:28:37 [Server] Server thread/CRITICAL #1 plugins/FactionsPE_v1.3.0.phar/src/fpe/command/Map(48): fpe\utils\Collections::getMap(object pocketmine\Player, integer 49, integer 8, integer 72)
01.01 06:28:37 [Server] Server thread/CRITICAL #2 plugins/FactionsPE_v1.3.0.phar/src/dominate/Command(522): fpe\command\Map->perform(object pocketmine\Player, string[1] f, array[0])
01.01 06:28:37 [Server] Server thread/CRITICAL #3 plugins/FactionsPE_v1.3.0.phar/src/dominate/Command(493): dominate\Command->execute(object pocketmine\Player, string[1] f, array[0])
01.01 06:28:37 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/command/SimpleCommandMap(248): dominate\Command->execute(object pocketmine\Player, string[1] f, array[0])
01.01 06:28:37 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/Server(1810): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[5] f map)
01.01 06:28:37 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/Player(2322): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[5] f map)
01.01 06:28:37 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(239): pocketmine\Player->chat(string[6] /f map)
01.01 06:28:37 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
01.01 06:28:37 [Server] Server thread/CRITICAL #9 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
01.01 06:28:37 [Server] Server thread/CRITICAL #10 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
01.01 06:28:37 [Server] Server thread/CRITICAL #11 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
01.01 06:28:37 [Server] Server thread/CRITICAL #12 pmsrc/src/pocketmine/Player(3273): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
01.01 06:28:37 [Server] Server thread/CRITICAL #13 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
01.01 06:28:37 [Server] Server thread/CRITICAL #14 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 73.196.42.2 53713, object raklib\protocol\EncapsulatedPacket, integer 0)
01.01 06:28:37 [Server] Server thread/CRITICAL #15 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
01.01 06:28:37 [Server] Server thread/CRITICAL #16 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
01.01 06:28:37 [Server] Server thread/CRITICAL #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
01.01 06:28:37 [Server] Server thread/CRITICAL #18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
01.01 06:28:37 [Server] Server thread/CRITICAL #19 pmsrc/src/pocketmine/Server(2156): pocketmine\snooze\SleeperHandler->sleepUntil(double 1609500517.72)
01.01 06:28:37 [Server] Server thread/CRITICAL #20 pmsrc/src/pocketmine/Server(1993): pocketmine\Server->tickProcessor()
01.01 06:28:37 [Server] Server thread/CRITICAL #21 pmsrc/src/pocketmine/Server(1587): pocketmine\Server->start()
01.01 06:28:37 [Server] Server thread/CRITICAL #22 pmsrc/src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[59] /pocketmine/, string[67] /pocketmine/plugins/)
01.01 06:28:37 [Server] Server thread/CRITICAL #23 pmsrc/src/pocketmine/PocketMine(302): pocketmine\server()
01.01 06:28:37 [Server] Server thread/CRITICAL #24 pmsrc(11): require(string[115] phar:///pocketmine/jar/pocketmine)

**Comment by Kris-Driv** [comment]
Thanks for reporting, I'll fix it today.
