### ISSUE TITLE
Plugin Crash

### ISSUE THREAD

**Issue by KareemDoezMc** [BlockHorizons/FactionsPE#95]
02.01 22:14:57 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/FactionsPE_v1.4.1.phar/src/BlockHorizons/FactionsPE/FactionsPE" at line 55
02.01 22:14:57 [Server] Server thread/CRITICAL #0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[35] BlockHorizons\FactionsPE\FactionsPE)
02.01 22:14:57 [Server] Server thread/CRITICAL #1 (): BaseClassLoader->{closure}(string[35] BlockHorizons\FactionsPE\FactionsPE)
02.01 22:14:57 [Server] Server thread/CRITICAL #2 (): spl_autoload_call(string[35] BlockHorizons\FactionsPE\FactionsPE)
02.01 22:14:57 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/plugin/PluginManager(167): class_exists(string[35] BlockHorizons\FactionsPE\FactionsPE, boolean 1)
02.01 22:14:57 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[89] /pocketmine/plugins/FactionsPE_v1, array[2])
02.01 22:14:57 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/Server(1530): pocketmine\plugin\PluginManager->loadPlugins(string[67] /pocketmine/plugins/)
02.01 22:14:57 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[59] /pocketmine/, string[67] /pocketmine/plugins/)
02.01 22:14:57 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/PocketMine(302): pocketmine\server()
02.01 22:14:57 [Server] Server thread/CRITICAL #8 pmsrc(11): require(string[115] phar:///pocketmine/jar/pocketmine)

**Comment by Kris-Driv** [comment]
I have a strong feeling that you're using an older (unsupported version) of pocketmine.

You must use php version 7.4^

Update php binary and/or pocketmine phar at: https://jenkins.pmmp.io/

**Comment by KareemDoezMc** [comment]
I'll check it out.
